#Total number of flights by airline and airport on a monthly b

CREATE OR REPLACE VIEW MONTHLY_FLIGHS_BY_AIRPORTS_AIRLINES
AS

 SELECT AIRLINE,ORIGIN_AIRPORT AS AIRPORT,MONTH_NAME,COUNT(DISTINCT FLIGHT_NUMBER) Total_Flights
 FROM public.flights f
 INNER JOIN public.Calendar c ON f.year=c.year and f.month=c.month and f.day=c.day
 GROUP BY AIRLINE,ORIGIN_AIRPORT,MONTH_NAME
 ORDER BY AIRLINE,MONTH_NAME
 ;
  
 #On time percentage of each airline for the year 2015 
CREATE OR REPLACE VIEW ON_TIME_AIRLINES_PCT_2015
AS
 
 SELECT AIRLINE,ROUND((SUM(ON_TIME)/count(FLIGHT_NUMBER)*1.0)*100,2) as PCT_ON_TIME
 FROM(
 SELECT a.AIRLINE,FLIGHT_NUMBER,CASE WHEN IFNULL(DEPARTURE_DELAY,0)=0 THEN 1.0 ELSE 0.0 END as ON_TIME
 FROM public.flights  f
 INNER JOIN public.AIRLINES a ON f.AIRLINE=a.IATA_CODE
 WHERE  YEAR=2015
   )
  GROUP BY AIRLINE
  ORDER BY PCT_ON_TIME DESC
 ;

# Airlines with the largest number of delays
CREATE OR REPLACE VIEW AIRLINES_WITH_LARGEST_DELAY
AS
 WITH max_delay 
 AS(
 SELECT AIRLINE,SUM(delay) delay
 FROM(
 SELECT a.AIRLINE,FLIGHT_NUMBER,CASE WHEN IFNULL(AIRLINE_DELAY,0)<>0  THEN 1.0 ELSE 0.0 END as delay
 FROM public.flights f
 INNER JOIN public.AIRLINES a ON f.AIRLINE=a.IATA_CODE
  )
  GROUP BY AIRLINE
  )
 SELECT AIRLINE, delay as DELAY_COUNT
 FROM max_delay
 WHERE delay = (SELECT MAX(delay) FROM max_delay)
 ;

#Cancellation reasons by airport

CREATE OR REPLACE VIEW CANCELLATION_REASONS_BY_AIRPORT
AS

SELECT  AIRPORT , 
   SUM(CASE WHEN CANCELLATION_REASON ='A' THEN 1 ELSE 0 END) AS Airline_Carrier,
   SUM(CASE WHEN CANCELLATION_REASON ='B' THEN 1 ELSE 0 END) AS Weather,
   SUM(CASE WHEN CANCELLATION_REASON ='C' THEN 1 ELSE 0 END) AS National_Air_System,
   SUM(CASE WHEN CANCELLATION_REASON ='D' THEN 1 ELSE 0 END) AS Security
FROM public.flights f
INNER JOIN public.AIRPORTS a ON  f.ORIGIN_AIRPORT = a.IATA_CODE
WHERE CANCELLATION_REASON IS NOT NULL
GROUP BY AIRPORT
ORDER BY AIRPORT
;


#Delay reasons by airport
CREATE OR REPLACE VIEW DELAY_REASON_BY_AIRPORT
AS

 SELECT AIRPORT ,
   SUM(CASE WHEN IFNULL(AIRLINE_DELAY,0)>0    THEN 1 ELSE 0 END) AS AIRLINE_DELAY,
   SUM(CASE WHEN IFNULL(SECURITY_DELAY,0)>0   THEN 1 ELSE 0 END)  AS SECURITY_DELAY,
   SUM(CASE WHEN IFNULL(AIR_SYSTEM_DELAY,0)>0 THEN 1 ELSE 0 END) AS AIR_SYSTEM_DELAY 
 FROM public.flights f
 INNER JOIN public.AIRPORTS a ON  f.ORIGIN_AIRPORT = a.IATA_CODE
 WHERE IFNULL(AIRLINE_DELAY,0)>0 OR IFNULL(SECURITY_DELAY,0) >0 OR IFNULL(AIR_SYSTEM_DELAY,0)>0
 GROUP BY AIRPORT
 ORDER BY AIRPORT
 ;
 

# Airline with the most unique routes


CREATE OR REPLACE VIEW AIRLINE_WITH_MOST_UNIQUE_ROUTES
AS
SELECT a.AIRLINE,SUM(route) as Unique_route
 FROM(
 SELECT c.AIRLINE,ORIGIN_AIRPORT , DESTINATION_AIRPORT, count(*) route
 FROM public.flights f
 INNER JOIN public.AIRLINES c ON  f.AIRLINE=c.IATA_CODE
 GROUP BY c.AIRLINE,ORIGIN_AIRPORT , DESTINATION_AIRPORT
  )a
 WHERE a.route=1
GROUP BY a.AIRLINE
ORDER BY Unique_route DESC
LIMIT 1
 ;  